Removed references to macrecovery from Makefile
quickemu-project/quickemu pull request #1000
Opened 2024-04-13 04:03 UTC by chasecovello

2024-04-13 05:08 UTC, zen0bit requested changes

2024-04-13 10:47 UTC, flexiondotorg requested changes
As @zen0bit commented, be sure to add `chuckcheck` to install and uninstall and keep `macrecovery` in the uninstall.

2024-04-13 19:20 UTC, chasecovello commented
I made those changes and squashed into one commit. Thanks!

2024-04-13 19:25 UTC, zen0bit approved these changes

2024-04-15 07:51 UTC, flexiondotorg approved these changes
LGTM

2024-04-15 07:51 UTC, merged