Remove not anymore needed iffi
quickemu-project/quickemu pull request #1097
Opened 2024-04-21 17:27 UTC by zen0bit

2024-04-21 17:41 UTC, lj3954 commented
List_csv should not be removed or deprecated. There is absolutely zero reason to do that.

2024-04-21 22:51 UTC, philclifford requested changes
You didn't intend to add easybashlib did you?

2024-04-22 00:16 UTC, zen0bit commented
> List_csv should not be removed or deprecated. There is absolutely zero reason to do that.

It isn't...

2024-04-22 01:22 UTC, philclifford commented
> It isn't...
It is, accidentally : 
```
./quickget list_csv
./quickget: line 175: os_not_supported: command not found
ERROR! You must specify a release.
 - Releases: ./quickget: line 198: releases_list_csv: command not found
```
not because the os_not_supported function fix is not in here yet, but because `list_csv` needs adding to the parameter case choices as well as `--list-csv` on line 3539.

2024-04-22 01:27 UTC, philclifford requested changes
with this removed list_csv needs adding to the `--list-csv|lc|list` case

2024-04-22 02:12 UTC, zen0bit commented
Not sure about proper commit naming

2024-04-22 05:31 UTC, zen0bit commented
> You didn't intend to add easybashlib did you?

You are right
one step

2024-04-23 08:03 UTC, zen0bit commented
Not there?

> @zen0bit I am going to work on merging this branch into master.

Should be good to go

2024-04-23 09:04 UTC, merged

2024-04-23 19:32 UTC, philclifford commented
@zen0bit you missed changing the os_info line for tuxedo.
I find using `grep` (`rg`) and `sed` ( `-i` ) to make such edits more reliable even than globals search/replace in gui editors ;-)

unless #1109 is merged please update the os_info entry so we get a pretty name.

2024-04-23 20:50 UTC, zen0bit commented
> @zen0bit you missed changing the os_info line for tuxedo. I find using `grep` (`rg`) and `sed` ( `-i` ) to make such edits more reliable even than globals search/replace in gui editors ;-)
> 
> unless #1109 is merged please update the os_info entry so we get a pretty name.

#1107