ci: Add quickget tests to github action
quickemu-project/quickemu pull request #1107
Opened 2024-04-23 09:14 UTC by zen0bit

tests:
1. List all supported OS with releases and editions
2. List infos about all supported OS
3. List all URLs of supported ISOs
4. Test all supported ISOs availability

2024-04-23 23:10 UTC, philclifford requested changes
Need to append the `tee`s where doing "for each whatever" otherwise the assets only tell us about zorin

2024-04-23 23:10 UTC, philclifford commented on .github/workflows/quickget-tests.yml
> +            echo -e "\n\n      ${os}" && ./quickget -12345 "${os}" | tee osinfo.txt
```suggestion
            echo -e "\n\n      ${os}" && ./quickget -12345 "${os}" | tee -a osinfo.txt
```

currently we only see zorin in the artifact so you need to append to get all

2024-04-23 23:10 UTC, philclifford commented on .github/workflows/quickget-tests.yml
> +            echo -e "\n\n      ${os}" && ./quickget -ua "${os}" | tee isoslist.txt
```suggestion
            echo -e "\n\n      ${os}" && ./quickget -ua "${os}" | tee -a isoslist.txt
```

2024-04-23 23:10 UTC, philclifford commented on .github/workflows/quickget-tests.yml
> +            echo -e "\n\n      ${os}" && ./quickget -ca "${os}" | tee isostest.txt
```suggestion
            echo -e "\n\n      ${os}" && ./quickget -ca "${os}" | tee -a isostest.txt
```

2024-04-24 10:37 UTC, philclifford commented
Something is broken, at least with check. The [CI run](https://github.com/quickemu-project/quickemu/actions/runs/8812654392/job/24188764463?pr=1107#step:3:554) shows a fail for latest minimal but currently we are fine.
 
```
  ./quickget -c openindiana 20231027 minimal
Testing if OI-hipster-minimal-20231027.iso is available... PASS
```

CI is missing the EDITION .  This only happens for OpenIndiana and Siduction (search log for '--' )

Also there's something odd with the reporting of ubuntus - e.g. [line 330](https://github.com/quickemu-project/quickemu/actions/runs/8812654392/job/24188764463?pr=1107#step:3:330) ... "FAIL - ... PASS"

2024-04-24 11:08 UTC, zen0bit commented
> Something is broken, at least with check. The [CI run](https://github.com/quickemu-project/quickemu/actions/runs/8812654392/job/24188764463?pr=1107#step:3:554) shows a fail for latest minimal but currently we are fine.
> 
> ```
>   ./quickget -c openindiana 20231027 minimal
> Testing if OI-hipster-minimal-20231027.iso is available... PASS
> ```
> 
> CI is missing the EDITION . This only happens for OpenIndiana and Siduction (search log for '--' )
> 
> Also there's something odd with the reporting of ubuntus - e.g. [line 330](https://github.com/quickemu-project/quickemu/actions/runs/8812654392/job/24188764463?pr=1107#step:3:330) ... "FAIL - ... PASS"

Investigating...
PS: That's exactly why I am pushing CI😉

2024-04-27 09:44 UTC, zen0bit commented
Tests will be reworked to work with...

2024-04-30 07:50 UTC, zen0bit commented
Maybe we can leave -ca and -ua arguments?

-u and -c will work like:
without argument = will show all OS like -ua -ca doing now
with OS argument = will show all url/checks for an OS
with OS release and/or edition = will show url/check for concrete release and/or edition

Hmm? :thinking:

2024-04-30 09:54 UTC, flexiondotorg requested changes

2024-04-30 09:54 UTC, flexiondotorg commented on .github/pull_request_template
> +<!-- Uncomment relevant sections fill relevant and delete options which are not applicable -->
Please can you submit this template via its own pull request.

2024-04-30 15:49 UTC, zen0bit commented
@flexiondotorg rebased on master and all requested solved...

2024-04-30 16:05 UTC, zen0bit commented on .github/workflows/quickget-tests.yml
> +          distros="$(./quickget | sed '/^$/q' | tail -n +3)"
I see, but we lost nice sorting and separated names in tests then
I like it like that...

I thinking more about..
My previous question:
Maybe we can leave -ca and -ua arguments?

2024-04-30 16:05 UTC, zen0bit commented on .github/workflows/quickget-tests.yml
> +          distros="$(./quickget | sed '/^$/q' | tail -n +3)"
I see, but we lost nice sorting and separated names in tests then
I like it like that...

I thinking more about..
My previous question:
Maybe we can leave -ca and -ua arguments?

2024-04-30 17:01 UTC, zen0bit commented on .github/workflows/quickget-tests.yml
> +          distros="$(./quickget | sed '/^$/q' | tail -n +3)"
PS: I wanna also separate checks to individual OS in PR
later...
So green mark will be in PR for (changed OS only) or All checked OS
Depends on change in PR
But that PR template first... #1127

2024-04-30 18:55 UTC, zen0bit commented
> Maybe we can leave -ca and -ua arguments?
> Hmm? 🤔

Done

2024-05-01 00:52 UTC, zen0bit commented
OK I am done here for now?
Few things still needs to be fixed,
 but that will be just finalization and catching few remaining bugs, I think...

2024-05-01 04:57 UTC, zen0bit commented
🚀

2024-05-01 06:53 UTC, TuxVinyards commented
Two pp's in SKIPPED.   Otherwise reads as 'Skype'. 

I'll be pleased when all the branches finally get merged. It's been a very active last couple of weeks.

2024-05-01 07:12 UTC, zen0bit commented
> Two pp's in SKIPPED. Otherwise reads as 'Skype'.
> 
> I'll be pleased when all the branches finally get merged. It's been a very active last couple of weeks.

I am trying to fix strange counting in checks right after SKIPPED...

2024-05-02 21:54 UTC, zen0bit commented
So beacuse @flexiondotorg not merged this yetwhen worked excelently.
And leaved it here for to long..
 I broke it yesterday. Don't know where problem is. Can't figure out why test not working anymore 🤯

2024-05-02 22:28 UTC, flexiondotorg requested changes
This pull request is large, sprawling and difficult to review. I kindly request that you refrain from submitting pull requests like this.

In the future, please submit pull requests that are contained to a single fix, a single feature or a focused refactor only. 

Some of the changes in this pull request introduce bugs, some are refactors for the sake of change, some incorrectly change code indentation, and yet there are also some legitimate fixes.

I'll have to think about what to do with this and figure out how to cherry pick the good work that exists in here.

2024-05-02 23:18 UTC, zen0bit commented
> This pull request is large, sprawling and difficult to review. I kindly request that you refrain from submitting pull requests like this.
> 
> In the future, please submit pull requests that are contained to a single fix, a single feature or a focused refactor only.
> 
> Some of the changes in this pull request introduce bugs, some are refactors for the sake of change, some incorrectly change code indentation, and yet there are also some legitimate fixes.
> 
> I'll have to think about what to do with this and figure out how to cherry pick the good work that exists in here.

I would like to, but I am almost one year in advance due to your "presence" as maintainer 🤗

What can I do?

Wait another year before all chqnges I want will be in? (And rebase evrything meanwhile thousand times like last half year?)

Sorry but that's maybe bit more your fault "as maintainer" then my.
That I have "A lot to merge"

2024-05-03 00:31 UTC, zen0bit commented
> I'll have to think about what to do with this and figure out how to cherry pick the good work that exists in here.

Just point which commits you don't like. I will delete them without effort.. @flexiondotorg

2024-05-03 11:53 UTC, zen0bit commented
see...

2024-05-03 14:03 UTC, zen0bit commented
Once more, why you don't want merge this? Speak about commit you don't like not a whole.

Everything is working better then in master...

2024-05-03 16:00 UTC, flexiondotorg commented
I have a full-time job and a family. Pack it in with the churlish remarks!

2024-05-03 23:55 UTC, zen0bit commented
> I have a full-time job and a family. Pack it in with the churlish remarks!

Exactly! Then I wonder even more...
Why are you redoing what's I already done?

Like sorry, but you are here the one, who are wasting our time which could belongs to families instead...

2024-05-06 22:05 UTC, flexiondotorg commented
I'm closing this pull request because:
- commits from this branch are already in master
- commits in the branch revert intended functionality in master
- or other pull requests exist for features in the pull request

The only exception is the parallel testing changes, for which I welcome a pull request so it can be reviewed and tested in isolation.

2024-05-06 22:05 UTC, closed without merging