Implement simple custom_config
quickemu-project/quickemu pull request #1112
Opened 2024-04-25 05:35 UTC by lj3954

Only image types img & iso are supported by quickemu, so throw an error if the file/url doesn't end in one of those. Quickget shouldn't require the user to specify the OS, so instead attempt to determine it from the file (vast majority will be Linux-based anyways). make_vm_config had to be slightly modified to allow for the possibility of full paths to image files.

2024-04-25 07:18 UTC, zen0bit commented
I like it but, just keep same structure also for custom VM

Only question is in "local mode".
If image should be moved or copied from previous location

I am for moving (saving space)

2024-04-30 07:07 UTC, zen0bit commented
Bit modified your create_config function in my PR #1107 
Check if I messed something...

2024-04-30 09:45 UTC, flexiondotorg requested changes
Please can you rebase against current master

2024-05-03 09:03 UTC, flexiondotorg commented
CLosed via https://github.com/quickemu-project/quickemu/pull/1143

2024-05-03 09:03 UTC, closed without merging