feat: Disable copy on write for disk images on btrfs
quickemu-project/quickemu pull request #1228
Opened 2024-05-14 21:27 UTC by TheMuso

According to qemu-img documentation, it is a no-op for other filesystems.

2024-05-21 17:17 UTC, lj3954 requested changes

2024-05-21 17:17 UTC, lj3954 commented on quickemu
> +        if ! ${QEMU_IMG} create -q -f "${disk_format}" -o lazy_refcounts=on,preallocation="${preallocation}",nocow=on "${disk_img}" "${disk_size}"; then
```suggestion
local qemu_img_params
        if [[ "${disk_format}" == "qcow2" ]; then
            qemu_img_params="lazy_refcounts=on,preallocation=${preallocation},nocow=on"
        else
            qemu_img_params="preallocation=${preallocation}"
        fi
        if ! ${QEMU_IMG} create -q -f "${disk_format}" -o "${qemu_img_params}" "${disk_img}" "${disk_size}"; then
```
lazy_refcounts and nocow are only options for qcow2 disks, and quickemu allows for disk format to be specified. We need to make sure that qemu-img is not passed invalid parameters for the format at hand.

2024-05-21 23:04 UTC, TheMuso commented
Sorry, my mad. It was a patch I was just carrying locally and decided to submit it.

As to your comment, I also noticed lazy_refcounts cannot work with raw images, so decided to include a fix for that. Let me know if you would prefer that to be separated out into a new PR.

2024-05-25 17:33 UTC, lj3954 approved these changes

2024-06-30 12:23 UTC, flexiondotorg approved these changes

2024-06-30 12:23 UTC, merged