chore(updated supported releases) Updated ParrotOS and NixOS
quickemu-project/quickemu pull request #1279
Opened 2024-06-15 12:40 UTC by EuroNutellaMan

Added support for:

- NixOS 24.05
- ParrotOS 6.1

Removed support for:

- NixOS 23.05
- ParrotOS 5.9

2024-06-15 21:27 UTC, lj3954 requested changes
I've suggested changes to allow quickget to dynamically find the latest 2 releases. 

In addition, please remove NixOS from the PR, #1266 includes changes for that operating system.

2024-06-15 21:27 UTC, lj3954 commented on quickget
> +    echo 6.1 6.0
```suggestion
    echo $(web_pipe "https://download.parrot.sh/parrot/iso/" | grep -o -P '(?<=href=")[0-9].*(?=/")' | sort -nr | head -n +2)
```

2024-06-16 21:15 UTC, EuroNutellaMan commented
I should have removed the NixOS changes

2024-06-19 17:01 UTC, EuroNutellaMan commented
I can't figure out why the lint shellcheck keeps failing (not too familiar with github yet), do you want me to close this PR and redo it with the suggested changes?

I assumed it was due to the 2nd commit in which I accepted your suggestion, which isn't properly formatted but for whatever reason it doesn't let me rename that commit.

2024-06-19 18:21 UTC, lj3954 commented
> I can't figure out why the lint shellcheck keeps failing (not too familiar with github yet), do you want me to close this PR and redo it with the suggested changes?
> 
> I assumed it was due to the 2nd commit in which I accepted your suggestion, which isn't properly formatted but for whatever reason it doesn't let me rename that commit.

It's because some of ShellCheck's lints don't align with the formatting used by quickemu. Please add this line above.

#shellcheck disable=SC2046,SC2005

2024-06-20 07:51 UTC, EuroNutellaMan commented
> > I can't figure out why the lint shellcheck keeps failing (not too familiar with github yet), do you want me to close this PR and redo it with the suggested changes?
> > 
> > I assumed it was due to the 2nd commit in which I accepted your suggestion, which isn't properly formatted but for whatever reason it doesn't let me rename that commit.
> 
> It's because some of ShellCheck's lints don't align with the formatting used by quickemu. Please add this line above.
> 
> #shellcheck disable=SC2046,SC2005

Where should I add it exactly?

2024-06-24 09:01 UTC, flexiondotorg approved these changes

2024-06-24 09:01 UTC, merged