Add proxmox-ve
quickemu-project/quickemu pull request #1518
Opened 2024-11-17 09:13 UTC by jackwasey

# Description

Add proxmox-ve

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Packaging (updates the packaging)
- [ ] Documentation (updates the documentation)

# Checklist:

- [x] I have performed a self-review of my code
- [x] I have tested my code in common scenarios and confirmed there are no regressions
- [ ] I have added comments to my code, particularly in hard-to-understand sections
- [ ] I have made corresponding changes to the documentation (*remove if no documentation changes were required*)

2024-11-17 18:36 UTC, lj3954 requested changes
Dynamically detecting releases is preferred in order to reduce maintenance burden.

2024-11-17 18:36 UTC, lj3954 commented on quickget
> +    local HASH="c96ad84eacbbcef299ab8f407f9602f832abb5ceb08a9aa288c1e1164df2da97"
```suggestion
    local HASH=""
```

2024-11-17 18:36 UTC, lj3954 commented on quickget
> +    echo 8.2-2
```suggestion
    echo $(web_pipe https://enterprise.proxmox.com/iso/ | grep proxmox-ve | grep -E -o '[0-9]+\.[0-9]+-[0-9]\.iso' | uniq | sort -ru | cut -d'.' -f 1-2)
```

2024-11-22 05:08 UTC, lj3954 approved these changes

2024-12-18 12:50 UTC, flexiondotorg commented
What is the use case for running Proxmox in a VM? I am cautious about merging this and getting issue reports about VM performance in Proxmox VE under Quickemu.

2024-12-20 19:15 UTC, philclifford commented
> What is the use case for running Proxmox in a VM? 

To play with/learn - I mean obviously no-one would do that in production or expect to not have issues of performance or with nesting... 
![image](https://github.com/user-attachments/assets/3da7d251-29f3-45e1-a7f6-f5a35693f7c1)

To enable Proxmox-VE users to have a comfortable place to try out upgrades or config changes safely.
To experiment with Proxmox clustering and VM live migration
To enable a further layer of inception possibilities for anyone needing a challenge.
To allow Proxmox users the possibility to contribute to and use `quicktest` on the next version.

2024-12-30 10:56 UTC, merged