Better specify release
quickemu-project/quickemu pull request #355
Opened 2022-02-17 17:21 UTC by zen0bit

2022-02-18 00:50 UTC, philclifford commented
Awesome where it works.  Sadly doesn't for those like `ubuntu-mate` which have adopted the "OS-flavour" style.
If you split at the "-" it should work with the current patterns but I'd suggest we'd need to also change the documented guidance so contributors are clear to **only** use "-" in OS identifiers when adopting an "OS-flavour" approach and name the `releases_ <whatever>()` appropriately.

2022-02-18 01:02 UTC, philclifford requested changes

2022-02-18 01:02 UTC, philclifford commented on quickget
> +    if os_support | grep -q "${OS}" ; echo $? == 0 > /dev/null ; then
this test is not working:
```./quickget xxx
ERROR! You must specify a release: ./quickget: line 2137: releases_xxx: command not found
```
which is the same error if you try `quickget ubuntu-mate` or any of the "${OS}-*" types

please both fix the test, and account for all the "*" wildcards in the tests above.

2022-02-19 12:10 UTC, flexiondotorg commented
Sorry, this pull request breaks quickemu.

2022-02-19 12:10 UTC, closed without merging