Add XeroLinux
quickemu-project/quickemu pull request #667
Opened 2023-03-07 00:49 UTC by zen0bit

[XeroLinux](https://xerolinux.xyz/)

Initial commit..

As you asked..
Test pls. @TechXero

2023-03-14 02:16 UTC, philclifford approved these changes
LGTM

2023-04-30 10:57 UTC, flexiondotorg commented
Please rebase against `master`.

2023-04-30 12:50 UTC, zen0bit commented
done

2023-04-30 22:44 UTC, philclifford requested changes

2023-04-30 22:44 UTC, philclifford commented on quickget
> +    vxlinux)            PRETTY_NAME="VX linux";;
That should be left as "VX Linux"

https://github.com/dessington/vx-linux/blob/d68b13d0a73afc7b8f3ef9649cfd17668947adca/README.md?plain=1#LL1C1-L1C1

2023-05-04 00:28 UTC, philclifford approved these changes

2023-06-14 08:47 UTC, merged