Add support for changing virtual sound hardware
quickemu-project/quickemu pull request #705
Opened 2023-05-01 00:09 UTC by chasecovello

As part of getting the OpenIndiana ISO to boot and install with the default settings, I found that it doesn't have Intel HDA support, which is currently the only sound hardware set up by quickemu. So I added a new option "sound_card" to set the virtual hardware to one of "intel-hda", "ac97", "es1370", "sb16", or "none".

OpenIndiana was changed to "ac97" by default, and I also changed FreeDOS to use "sb16" since as far as I know there's no HDA driver for DOS and Sound Blaster was widely supported. This should also support, for example, older versions of Windows (XP, Vista) that don't come with HDA drivers.

2023-07-05 13:23 UTC, philclifford commented on docs/quickemu.1.md
> +      --delete-disk, --delete           : Delete the disk image and EFI variables
intentionally undocumented legacy non-specificity support

2023-07-05 13:29 UTC, philclifford commented on docs/quickemu.1
> +`sdl' (default), `gtk', `none', `spice', or `spice-app'
Good spot - that needs aligning in the short option section.
I'll transfer that in to the docs sub-module.

2023-07-05 13:32 UTC, philclifford commented on quickemu
> +  echo "  --delete-disk, --delete           : Delete the disk image and EFI variables"
this option intentionally made more specific and the old version undocumented

2023-07-05 13:34 UTC, philclifford commented on quickemu
> +# options: intel-hda, ac97, es1370, sb16, none
better below sound_card than mouse

2023-07-05 13:35 UTC, philclifford commented on quickemu
> +  echo "  --public-dir <path>               : Expose share directory. @Options: '' (default: xdg-user-dir PUBLICSHARE), '<directory>', 'none'"
:+1:

2023-07-05 13:46 UTC, philclifford requested changes
Thanks @chasecovello .  Could you please remove the docs changes from the PR : apart from the one I've noted those sections of the manuals are generated from the usage() output to try and ensure alignment at release and also try and avoid trivial git conflicts in the docs requiring contributors to keep rebasing and resolving.  A discussion could be had about only having one comprehensive options section. If you could just include the changes in `quickemu` in this PR the docs should take care of themselves.

Many thanks, and sorry I took so long to get to this!

2023-07-05 16:00 UTC, chasecovello commented
Thank you! I've reverted the docs commit and re-added the capitalization fix in the quickemu options summary.

2023-07-06 18:34 UTC, philclifford approved these changes
LGTM
Thanks! It would be good if you could squash those commits to keep the history tidy (and if a maintainer squashes the merge the authorship can be clobbered)

2023-07-06 19:19 UTC, chasecovello commented
Done. Rebased to upstream/master with a single commit.

2023-07-06 20:58 UTC, philclifford commented
Thanks.

2023-10-16 10:41 UTC, merged