Updated manjaro fetching as migrated to new system
quickemu-project/quickemu pull request #742
Opened 2023-09-08 18:45 UTC by Jai-JAP

- Updated get_manjaro() implementation to support fetching latest released versions
- Added sway release
- Added choice to download minimal or full edition

2023-09-15 01:28 UTC, philclifford approved these changes

2023-10-11 19:56 UTC, zen0bit requested changes

2023-10-11 19:56 UTC, zen0bit commented on quickget
> +        URL="echo ${MANIFEST} | jq -r '.[] | select(.name|test("^manjaro-sway-.*[.]iso$")) | select(.name|contains("unstable")|not) | .url'"
Don't work for me...

If i changed line to this it worked

`URL=$(echo ${MANIFEST} | jq -r '.[] | select(.name|test("^manjaro-sway-.*[.]iso$")) | select(.name|contains("unstable")|not) | .url')`

2023-10-11 19:58 UTC, zen0bit commented on quickget
> +        URL="echo ${MANIFEST} | jq -r '.[] | select(.name|test("^manjaro-sway-.*[.]iso$")) | select(.name|contains("unstable")|not) | .url'"
URL=$(echo ${MANIFEST} | jq -r '.[] | select(.name|test("^manjaro-sway-.*[.]iso$")) | select(.name|contains("unstable")|not) | .url')

2023-10-11 19:59 UTC, zen0bit requested changes
Work for me with changed line 1516

2023-10-12 03:50 UTC, zen0bit approved these changes

2023-10-16 10:35 UTC, merged