Add Athena OS
quickemu-project/quickemu pull request #750
Opened 2023-09-13 23:28 UTC by zen0bit

2023-09-15 02:32 UTC, philclifford approved these changes

2023-10-04 23:14 UTC, zen0bit commented
![athenaos](https://github.com/quickemu-project/quickemu/assets/6384793/141fc1ad-21f5-4dca-a99a-e37d0e7e4f5a)

2023-10-19 08:33 UTC, flexiondotorg requested changes
Please rebase this one.

2023-11-13 07:16 UTC, zen0bit commented
ready

2023-12-30 23:27 UTC, zen0bit commented
continues in #892

2023-12-30 23:27 UTC, closed without merging