Add bazzite
quickemu-project/quickemu pull request #797
Opened 2023-10-12 04:41 UTC by zen0bit

2023-10-19 08:19 UTC, flexiondotorg requested changes
This pull request clatter bodhi.

I think it would also be wise to use `jq` to dynamically get the current release of Bazzite rather than hardcode release version. Bazzite release fairly often.

2023-10-24 15:47 UTC, zen0bit commented on quickget
good to go

2023-11-07 16:28 UTC, zen0bit commented
Tested with new release 2.0.0

2023-11-13 07:19 UTC, zen0bit commented
ready

2023-12-14 03:58 UTC, zen0bit commented
Tested with latest release...

2023-12-30 23:26 UTC, zen0bit commented
continues in #892

2023-12-30 23:26 UTC, closed without merging