Add SparkyLinux
quickemu-project/quickemu pull request #799
Opened 2023-10-12 08:10 UTC by zen0bit

![sparky](https://github.com/quickemu-project/quickemu/assets/6384793/d32bf672-e643-490a-ad9e-82798e76233f)

2023-10-19 08:20 UTC, flexiondotorg approved these changes

2023-10-19 08:20 UTC, flexiondotorg requested changes
Please rebase the pull request

2023-11-13 07:18 UTC, zen0bit commented
ready

2023-12-21 11:42 UTC, zen-oSoWoSo approved these changes

2023-12-30 23:26 UTC, zen0bit commented
continues in #892

2023-12-30 23:26 UTC, closed without merging