Small --help improvement
quickemu-project/quickemu pull request #808
Opened 2023-10-17 17:56 UTC by stone-w4tch3r

It took me to review source code to understand how additional params work, so created this PR)

2023-10-17 20:00 UTC, zen0bit commented
docs will be regenerated from files.

look here 
https://github.com/philclifford/quickemu-docs

2023-10-19 10:58 UTC, philclifford requested changes
Please rebase/re-factor to only change `quickemu`.  The rest will be automatically updated via `cog` and `pandoc`

2023-10-21 17:57 UTC, stone-w4tch3r commented
Removed unnecessary changes, code ready fr merge ;-)

2023-10-23 00:32 UTC, philclifford approved these changes

2023-10-26 15:03 UTC, closed without merging