Added automatic version fetching for ubuntu
quickemu-project/quickemu pull request #821
Opened 2023-10-24 10:12 UTC by Jai-JAP

- Fetch ubuntu versions directly from https://api.launchpad.net/devel/ubuntu/series (desktop flavors) and http://releases.ubuntu.com/streams/v1/com.ubuntu.releases:ubuntu-server.json (Server)
 - Remove obsolete releases {daily-canary, jammy-daily}
 - Format documents with shfmt

2023-10-24 15:25 UTC, philclifford commented
Excellent!

One tweak though - jammy-daily is not quite obsolete :

https://cdimage.ubuntu.com/jammy/daily-live/current/ 
https://iso.qa.ubuntu.com/qatracker/milestones/429/builds

2023-10-24 16:10 UTC, Jai-JAP commented
> Excellent!
> 
> One tweak though - jammy-daily is not quite obsolete :
> 
> https://cdimage.ubuntu.com/jammy/daily-live/current/ 
> https://iso.qa.ubuntu.com/qatracker/milestones/429/builds
> 

I'll fix that soon.

2023-10-24 18:08 UTC, Jai-JAP commented
jammy-daily should be back working now

2023-10-24 23:46 UTC, philclifford commented
Thanks

2023-10-24 23:48 UTC, philclifford approved these changes

2023-11-09 09:40 UTC, flexiondotorg requested changes
I can not accept pull requests that change the indentation project wide.

2023-11-09 13:49 UTC, Jai-JAP commented
> I can not accept pull requests that change the indentation project wide.

I will fix that soon.

2023-11-10 10:29 UTC, flexiondotorg commented
This patch is massive:

![image](https://github.com/quickemu-project/quickemu/assets/304639/0d708758-4528-481f-8caf-a318733a3d0b)

Please refactor this pull request to only provide the changes to add automatic version fetching for Ubuntu and **remove all whitespace-related changes**.

2023-11-10 19:22 UTC, Jai-JAP commented
@flexiondotorg ig the changes you requested are resolved.

2023-11-10 20:48 UTC, philclifford approved these changes

2023-11-12 19:06 UTC, philclifford requested changes
The purely-whitespace changes would be better dealt with in another (possibly existing) PR. (But at least now they are restricted to a couple of functions. - this is not a show-stopper for me but ...)
 
The results do not correctly align with the available releases so there is either a flaw in the logic or in what the api presents.
Some examples below (`./quickget` is the PR version) showing missing 23.10 interims , missing `jammy-daily` options and non-existent early releases.

```shell
$
$quickget ubuntu-unity
ERROR! You must specify a release.
 - Releases: 23.04 23.10 daily-live daily-canary
$./quickget ubuntu-unity
ERROR! You must specify a release.
 - Releases: 23.04 daily-live
$quickget xubuntu
ERROR! You must specify a release.
 - Releases: 16.04 18.04 20.04 22.04 23.04 23.10 jammy-daily daily-live daily-canary daily-legacy                                                                        
$./quickget xubuntu
ERROR! You must specify a release.
 - Releases: 14.04 16.04 18.04 20.04 22.04 23.04 23.10 daily-live daily-legacy jammy-daily                                
$quickget ubuntucinnamon
ERROR! You must specify a release.
 - Releases: 23.04 23.10 daily-live daily-canary
$./quickget ubuntucinnamon
ERROR! You must specify a release.
 - Releases: 23.04 daily-live
$quickget ubuntu-server
ERROR! You must specify a release.
 - Releases: 18.04 20.04 22.04 23.04 23.10 daily-live
$./quickget ubuntu-server
ERROR! You must specify a release.
 - Releases: 18.04 20.04 22.04 23.04 23.10 daily-live
$quickget ubuntu
ERROR! You must specify a release.
 - Releases: 14.04 16.04 18.04 20.04 22.04 23.04 23.10 jammy-daily daily-live daily-canary daily-legacy    
$./quickget ubuntu
ERROR! You must specify a release.
 - Releases: 14.04 16.04 18.04 20.04 22.04 23.04 23.10 daily-live daily-legacy                                                                     
$quickget ubuntu-mate
ERROR! You must specify a release.
 - Releases: 16.04 18.04 20.04 22.04 23.04 23.10 jammy-daily daily-live daily-canary daily-legacy                                                                        
$./quickget ubuntu-mate
ERROR! You must specify a release.
 - Releases: 14.04 16.04 18.04 20.04 22.04 23.04 23.10 daily-live daily-legacy jammy-daily         
```

2023-11-13 03:04 UTC, Jai-JAP commented on quickget
> +
> Should not be changing vanillaos or other non-ubuntu functions in this PR

I didn't make any manual changes here. Maybe editorconfig automatically removing trailing whitespaces.

2023-11-13 03:10 UTC, Jai-JAP commented
@philclifford the version of quickget u are using is not from this PR as it removed all traces of daily-canary which is present in your output

2023-11-14 15:42 UTC, Jai-JAP commented
@philclifford Everything should be working fine now. Can you test again?

2023-11-15 02:26 UTC, Jai-JAP commented
@philclifford Edubuntu is fixed now.

2023-11-16 23:35 UTC, merged