New master merge
quickemu-project/quickemu pull request #986
Opened 2024-04-09 06:17 UTC by zen0bit

2024-04-09 06:45 UTC, TuxVinyards commented
Good work 👍

2024-04-09 07:27 UTC, zen0bit commented
I am not done yet... :rofl:

2024-04-10 23:32 UTC, lj3954 requested changes

2024-04-10 23:32 UTC, lj3954 commented on quickget
This distro appears to have different latest releases for KDE and GNOME. The release you put is the latest release of GNOME CachyOS, but is invalid for KDE. I think instead, you should just put 'latest' and handle everything else in the get_cachyos function.

2024-04-10 23:32 UTC, lj3954 commented on quickget
Here's the fixed 'get_cachyos' function to go along with that.

```bash
function get_cachyos() {
    local HASH=""
    local latest_release
    latest_release=$(curl "https://mirror.cachyos.org/ISO/${EDITION}/" | grep -Po '(?<=">)[0-9]+(?=/</a>)' | tail -n 1)

    local ISO="cachyos-${EDITION}-linux-${latest_release}.iso"
    local URL="https://mirror.cachyos.org/ISO/${EDITION}/${latest_release}"
    HASH=$(wget -q -O- "${URL}/${ISO}.sha256" | cut -d' ' -f1)
    echo "${URL}/${ISO} ${HASH}"
}
```

2024-04-10 23:32 UTC, lj3954 commented on quickget
> +    echo 240121
```suggestion
    echo latest
```

2024-04-11 21:08 UTC, merged